/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpServer;
import org.apache.commons.io.IOUtils;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;

import java.io.*;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class Ingestor {

    public static final String INGEST_TOPIC = "ingested-things";
    private static HttpServer server;
    private static Producer<String, String> producer;

    public static void main(String[] args) throws Exception {
        Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("acks", "all");
        props.put("retries", 0);
        props.put("batch.size", 16384);
        props.put("linger.ms", 1);
        props.put("buffer.memory", 33554432);
        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        producer = new KafkaProducer<>(props);
        startServer();
    }

    private static void startServer() throws Exception {
        server = HttpServer.create(new InetSocketAddress(8000), 0);
        server.createContext("/ingest", t -> {
            final String value = IOUtils.toString(t.getRequestBody(), StandardCharsets.UTF_8);
            final Future<RecordMetadata> sendFuture = producer.send(new ProducerRecord<>(INGEST_TOPIC, value));
            final RecordMetadata recordMetadata;
            try {
                recordMetadata = sendFuture.get(5000, TimeUnit.SECONDS);
            } catch (InterruptedException | TimeoutException | ExecutionException e) {
                throw new RuntimeException("Failed to produce record", e);
            }
            final String response = String.format("Value was sent to %s at %d\n", INGEST_TOPIC, recordMetadata.timestamp());
            t.sendResponseHeaders(200, response.length());
            OutputStream os = t.getResponseBody();
            os.write(response.getBytes());
            os.close();
        });
        new Thread(() -> server.start(), "HTTP Server").start();
    }
}
