---
services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin